### ISSUE TITLE
azureWebAppPublish with option to use existing image instead of building one

### ISSUE THREAD

**Issue by schdief** [Microsoft/azure-app-service-plugin#25] opened 2018-01-07 16:19 UTC
I'm using the plugin to deploy to Azure App Services. It would be great to have an option, which would use an existing image (in the specified registry with the specified name and tag) instead of always building a new one. Within my Jenkinsfile I do multiple deployments of the same webapp to have different environments, e. g. for functional tests with webdriver.io or performance tests with octoperf, to avoid conflicts when running them on the same environment. After those test I do another deployment in to production. In this case I would build the image 3 times instead of once. Furthermore I can't be sure that the same image will be used for production as in test, since it is another build. Lastly I can't define any build-args for this build, but I need them to set the environment variables during build (e. g. the release name with git commit id).

My current request looks like this:
`azureWebAppPublish azureCredentialsId: 'azure', publishType: 'docker', resourceGroup: "moveezRG", appName: "${packageJSON.name}", dockerImageName: "schdieflaw/${packageJSON.name}", dockerImageTag: "${packageJSON.version}_${env.BUILD_ID}", dockerRegistryEndpoint: [credentialsId: 'dockerhub', url: "https://registry.hub.docker.com"]`

With that option it could be like this:
`azureWebAppPublish azureCredentialsId: 'azure', publishType: 'docker', resourceGroup: "moveezRG", appName: "${packageJSON.name}", dockerImageName: "schdieflaw/${packageJSON.name}", dockerImageTag: "${packageJSON.version}_${env.BUILD_ID}", dockerBuild: false, dockerRegistryEndpoint: [credentialsId: 'dockerhub', url: "https://registry.hub.docker.com"]`

**Comment by ArchangelSDY** [comment] 2018-01-08 06:54
Sounds reasonable. I will work on a patch. Thanks for your feedback!

**Comment by ArchangelSDY** [comment] 2018-01-09 08:40
The new option will be called `skipDockerBuild` to keep backward compatibility. The patch already landed in master branch but since we just made a release this week, the next release might be weeks later. You can clone the code and build it by yourself to install the pre-release version.

**Comment by schdief** [comment] 2018-01-09 18:40
@ArchangelSDY thanks for providing the feature so fast! I've tried it and in general it works. Quite often unfortunately I get a "Service Unavailable" and I have no clue why. As mentioned above I do 3 parallel deployments and the last time I've tried this was the result:

http://moveez-functional.azurewebsites.net: Service Unavailable
http://moveez-explorative.azurewebsites.net: OK
http://moveez-performance.azurewebsites.net: OK

I've tried several different things like sleep(60) or retry(5) but nothing seems to do the job.

This is the corresponding code:
`stage('UAT') {
            steps {
        		parallel(
        			'PERFORMANCE': {
                        //deploy environment for performance test via docker image from dockerhub on azure webapp service
                        azureWebAppPublish azureCredentialsId: 'azure', publishType: 'docker', resourceGroup: "moveezRG", appName: "${packageJSON.name}", slotName: "performance", dockerImageName: "schdieflaw/${packageJSON.name}", dockerImageTag: "${packageJSON.version}_${env.BUILD_ID}", skipDockerBuild: true, dockerRegistryEndpoint: [credentialsId: 'dockerhub', url: "https://registry.hub.docker.com"]
                        //check the deployment
                        retry(5) {
                            httpRequest responseHandle: 'NONE', url: 'http://moveez-performance.azurewebsites.net', validResponseCodes: '200', validResponseContent: 'Welcome'
                        }
                        //run performance test using octoperf
                        octoPerfTest credentialsId: 'octoperf', scenarioId: 'AWDRqMX0yJH_vau-VobL', stopConditions: [stopOnAlert(buildResult: 'UNSTABLE', severity: 'CRITICAL')]
                    },
        			'EXPLORATIVE': {
        				//deploy environment for explorative test via docker image from dockerhub on azure webapp service
                        azureWebAppPublish azureCredentialsId: 'azure', publishType: 'docker', resourceGroup: "moveezRG", appName: "${packageJSON.name}", slotName: "explorative", dockerImageName: "schdieflaw/${packageJSON.name}", dockerImageTag: "${packageJSON.version}_${env.BUILD_ID}", skipDockerBuild: true, dockerRegistryEndpoint: [credentialsId: 'dockerhub', url: "https://registry.hub.docker.com"]
                        //check the deployment
                        retry(5) {
                            httpRequest responseHandle: 'NONE', url: 'http://moveez-explorative.azurewebsites.net', validResponseCodes: '200', validResponseContent: 'Welcome'
                        }
                    },
                    'ACCEPTANCE': {
                        //deploy environment for acceptance test via docker image from dockerhub on azure webapp service
                        azureWebAppPublish azureCredentialsId: 'azure', publishType: 'docker', resourceGroup: "moveezRG", appName: "${packageJSON.name}", slotName: "functional", dockerImageName: "schdieflaw/${packageJSON.name}", dockerImageTag: "${packageJSON.version}_${env.BUILD_ID}", skipDockerBuild: true, dockerRegistryEndpoint: [credentialsId: 'dockerhub', url: "https://registry.hub.docker.com"]
                        //check the deployment
                        retry(5) {
                            httpRequest responseHandle: 'NONE', url: 'http://moveez-functional.azurewebsites.net', validResponseCodes: '200', validResponseContent: 'Welcome'
                        }
                        //run acceptance test with cucumber and webdriverio
                        sh "cd ./test/acceptance && ../../node_modules/.bin/wdio wdio.conf.js"
                    }
        		)
            }
        }`

**Comment by ArchangelSDY** [comment] 2018-01-10 03:54
I did some experiments using some official images like `nginx:latest` and `tomcat:latest` but I can't reproduce the issue. There is some downtime during deployment but finally it will run. Have you tried:

1. Deploy 3 apps one by one instead of in parallel.
2. Deploy just 1 app. Will it always succeed?
3. Deploy manually or use some other tool such as Azure CLI to see if it's a particular issue of Jenkins Plugin.

**Comment by juniwang** [comment] 2018-01-10 04:12
All three web apps are now Service Unvailable now.  Please try other options as above. Besides, please also try the image in your local docker engine. It might show your more logs about it.

**Comment by schdief** [comment] 2018-01-21 14:49
@ArchangelSDY and @juniwang first of all sorry for the late reply but since this is a private project I don't always find the time for it :(

I wanted to do some testing and created this very simple jenkins pipeline (see below). But I get the error message (full log below): "ERROR: Publish a windows or built-in image web app through docker is not currently supported."

So I thought I did something wrong with my jenkinsfile and tried my old build which worked 13 days ago and it failed with the same message. I'm still using the same custom build plugin version and I didn't change any jenkins settings. My azure subscription is also still valid, any ideas? Thanks for your help!

Simple jenkinsfile:
node{
    azureWebAppPublish azureCredentialsId: 'azure', publishType: 'docker', resourceGroup: "moveezRG", appName: "moveez", slotName: "performance", dockerImageName: "schdieflaw/moveez", dockerImageTag: "latest", skipDockerBuild: true, dockerRegistryEndpoint: [credentialsId: 'dockerhub', url: "https://registry.hub.docker.com"]
}

Log:
[Pipeline] node
Running on Jenkins in /var/lib/jenkins/workspace/Azure App Service Deployment Test
[Pipeline] {
[Pipeline] azureWebAppPublish
Starting Azure Web App Deployment
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: Publish a windows or built-in image web app through docker is not currently supported.
Finished: FAILURE

**Comment by ArchangelSDY** [comment] 2018-01-23 03:12
Please make sure the Web App you created is a Linux one and not configured with Azure built-in image(Node.JS/PHP...).

**Comment by schdief** [comment] 2018-01-23 19:43
Today I've just set up the whole configuration again like described here:
https://docs.microsoft.com/de-de/azure/app-service/containers/tutorial-custom-docker-image

This is the CLI output:
```
Steves-MacBook-Pro:~ schdief$ az group create --name pluginTestRG --location "West Europe"
{
  "id": "/subscriptions/0848c798-131c-4d65-ac2c-05b606da73e5/resourceGroups/pluginTestRG",
  "location": "westeurope",
  "managedBy": null,
  "name": "pluginTestRG",
  "properties": {
    "provisioningState": "Succeeded"
  },
  "tags": null
}
Steves-MacBook-Pro:~ schdief$ az appservice plan create --name pluginTestP --resource-group pluginTestRG --sku S1 --is-linux
{
  "adminSiteName": null,
  "appServicePlanName": "pluginTestP",
  "geoRegion": "West Europe",
  "hostingEnvironmentProfile": null,
  "id": "/subscriptions/0848c798-131c-4d65-ac2c-05b606da73e5/resourceGroups/pluginTestRG/providers/Microsoft.Web/serverfarms/pluginTestP",
  "isSpot": false,
  "kind": "linux",
  "location": "West Europe",
  "maximumNumberOfWorkers": 10,
  "name": "pluginTestP",
  "numberOfSites": 0,
  "perSiteScaling": false,
  "provisioningState": "Succeeded",
  "reserved": true,
  "resourceGroup": "pluginTestRG",
  "sku": {
    "capabilities": null,
    "capacity": 1,
    "family": "S",
    "locations": null,
    "name": "S1",
    "size": "S1",
    "skuCapacity": null,
    "tier": "Standard"
  },
  "spotExpirationTime": null,
  "status": "Ready",
  "subscription": "0848c798-131c-4d65-ac2c-05b606da73e5",
  "tags": null,
  "targetWorkerCount": 0,
  "targetWorkerSizeId": 0,
  "type": "Microsoft.Web/serverfarms",
  "workerTierName": null
}
Steves-MacBook-Pro:~ schdief$ az webapp create --resource-group pluginTestRG --plan pluginTestP --name pluginTestApp --deployment-container-image-name schdieflaw/moveez:latest
{
  "availabilityState": "Normal",
  "clientAffinityEnabled": true,
  "clientCertEnabled": false,
  "cloningInfo": null,
  "containerSize": 0,
  "dailyMemoryTimeQuota": 0,
  "defaultHostName": "plugintestapp.azurewebsites.net",
  "enabled": true,
  "enabledHostNames": [
    "plugintestapp.azurewebsites.net",
    "plugintestapp.scm.azurewebsites.net"
  ],
  "ftpPublishingUrl": "ftp://waws-prod-am2-137.ftp.azurewebsites.windows.net/site/wwwroot",
  "hostNameSslStates": [
    {
      "additionalProperties": {
        "ipBasedSslResult": null,
        "ipBasedSslState": "NotConfigured",
        "toUpdateIpBasedSsl": null
      },
      "hostType": "Standard",
      "name": "plugintestapp.azurewebsites.net",
      "sslState": "Disabled",
      "thumbprint": null,
      "toUpdate": null,
      "virtualIp": null
    },
    {
      "additionalProperties": {
        "ipBasedSslResult": null,
        "ipBasedSslState": "NotConfigured",
        "toUpdateIpBasedSsl": null
      },
      "hostType": "Repository",
      "name": "plugintestapp.scm.azurewebsites.net",
      "sslState": "Disabled",
      "thumbprint": null,
      "toUpdate": null,
      "virtualIp": null
    }
  ],
  "hostNames": [
    "plugintestapp.azurewebsites.net"
  ],
  "hostNamesDisabled": false,
  "hostingEnvironmentProfile": null,
  "httpsOnly": false,
  "id": "/subscriptions/0848c798-131c-4d65-ac2c-05b606da73e5/resourceGroups/pluginTestRG/providers/Microsoft.Web/sites/pluginTestApp",
  "identity": null,
  "isDefaultContainer": null,
  "kind": "app",
  "lastModifiedTimeUtc": "2018-01-23T19:08:32.720000",
  "location": "West Europe",
  "maxNumberOfWorkers": null,
  "name": "pluginTestApp",
  "outboundIpAddresses": "52.233.175.59,52.174.167.45,40.68.252.87,52.174.162.33,52.178.24.39",
  "possibleOutboundIpAddresses": "52.233.175.59,52.174.167.45,40.68.252.87,52.174.162.33,52.178.24.39",
  "repositorySiteName": "pluginTestApp",
  "reserved": true,
  "resourceGroup": "pluginTestRG",
  "scmSiteAlsoStopped": false,
  "serverFarmId": "/subscriptions/0848c798-131c-4d65-ac2c-05b606da73e5/resourceGroups/pluginTestRG/providers/Microsoft.Web/serverfarms/pluginTestP",
  "siteConfig": null,
  "slotSwapStatus": null,
  "snapshotInfo": null,
  "state": "Running",
  "suspendedTill": null,
  "tags": null,
  "targetSwapSlot": null,
  "trafficManagerHostNames": null,
  "type": "Microsoft.Web/sites",
  "usageState": "Normal"
}

```
With the result:
http://plugintestapp.azurewebsites.net/title -> works

When I then try to run this pipeline:
```
node{
    azureWebAppPublish appName: 'pluginTestApp', publishType: 'docker', azureCredentialsId: 'azure', dockerImageName: 'schdieflaw/moveez', dockerImageTag: 'latest', dockerRegistryEndpoint: [credentialsId: 'dockerhub', url: "https://registry.hub.docker.com"], resourceGroup: 'pluginTestRG', slotName: ''
}
```

It results in the same error:
```
[Pipeline] node
Running on Jenkins in /var/lib/jenkins/workspace/Azure App Service Deployment Test
[Pipeline] {
[Pipeline] azureWebAppPublish
Starting Azure Web App Deployment
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: Publish a windows or built-in image web app through docker is not currently supported.
Finished: FAILURE
```

When I use the script generator there is no option for "docker" and it generates a combination of docker and file publishing:
`azureWebAppPublish appName: 'pluginTestApp', azureCredentialsId: 'azure', dockerImageName: '', dockerImageTag: '', dockerRegistryEndpoint: [], filePath: '', publishType: 'file', resourceGroup: 'pluginTestRG', slotName: '', sourceDirectory: '', targetDirectory: ''`

<img width="838" alt="snippet" src="https://user-images.githubusercontent.com/10979159/35296801-7dadf900-007d-11e8-8f16-679cfbc06a73.png">

So from my point of view it is a problem with the plugin.

**Comment by juniwang** [comment] 2018-01-24 03:15
I believe the issue is related to https://github.com/jenkinsci/azure-app-service-plugin/blob/dev/src/main/java/com/microsoft/jenkins/appservice/WebAppDeploymentRecorder.java#L283.

**Comment by juniwang** [comment] 2018-01-24 03:18
Azure app service team changed the `kind` of webapp many times. It's `app` in the beginning and then `app,linux` and now `app,linux,container`. The change broken us again. I suggest using the old way by checking the `linuxFxVersion` to check whether a webapp is linux container or not

**Comment by ArchangelSDY** [comment] 2018-01-24 03:25
Well, I found `linuxFxVersion` is not always set for a Linux app. That's why I changed to checking `kind` field in last commit. Maybe we can loose the condition a bit to `kind.constains('linux')`?

**Comment by juniwang** [comment] 2018-01-24 04:01
Then let's try to find a relatively robust way to determine a webapp is linux-based or not

**Closed** 2018-01-25 08:07 UTC

**Comment by ArchangelSDY** [comment] 2018-01-25 08:28
@schdief The new fix has landed in master branch. Could you have a try?

**Comment by schdief** [comment] 2018-01-25 19:13
@ArchangelSDY this fix worked:
[Pipeline] node
Running on Jenkins in /var/lib/jenkins/workspace/Azure App Service Deployment Test
[Pipeline] {
[Pipeline] azureWebAppPublish
Starting Azure Web App Deployment
Updating configuration of Azure app service `pluginTestApp`, with new docker image schdieflaw/moveez:latest.
Azure app service updated successfully.
Done Azure Web App deployment.
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: SUCCESS

so I got back to the original problem of it not working when done in parallel and this issue still persists, but I don't have more time today to play around, will try it on saturday
